### ISSUE TITLE
Copy icon in the top left corner is not visible

### ISSUE THREAD

**Issue by RajeevDash007** [henicosa/PartiDeck#10]

**Comment by henicosa** [comment]
Problem:
We used to have a button to switch from card view to overview:

![grafik](https://github.com/henicosa/PartiDeck/assets/49242055/6286194d-92c4-4d12-a10f-6ad78c04ccd7)

But now the icon for the button is not visible anymore:
![grafik](https://github.com/henicosa/PartiDeck/assets/49242055/60ce3297-a09a-4e8c-80be-1eb4dcaf51ce)

Task: Make the button appear again.

**Comment by jan-gfrerer** [comment]
Nice first issue
