### ISSUE TITLE
Make text on card scale with card

### ISSUE THREAD

**Issue by henicosa** [henicosa/PartiDeck#11]
Problem:
So, write now we have sometimes titles that are too long to fit on one card:
![grafik](https://github.com/henicosa/PartiDeck/assets/49242055/d76ef7c9-fe26-422c-bacb-9439ae3e88fb)

But this problem gets even worse when we change the aspect ratio of the window:
![grafik](https://github.com/henicosa/PartiDeck/assets/49242055/e382f347-4b56-4024-a7db-45a401009506)

Proposed Solution: The text on cards should scale with the cards.

**Comment by RajeevDash007** [comment]
we can use calc() to solve this use
