### ISSUE TITLE
WEBSITE support item selection via query string

### ISSUE THREAD

**Issue by henicosa** [henicosa/PartiDeck#2]
parse the query string "henicosa.github.io/PartiDeck/?item=34" with Javascript and make use of the item value to select the correct method from the participation dataset for display

#goodfirstissue

**Comment by vedantmistryy** [comment]
@henicosa Kindly explain more
Regards.

**Comment by vedantmistryy** [comment]
I'm so sorry, I am still learning Javascript and I don't think I can solve this, you can understand.

**Comment by henicosa** [comment]
No worries! Maybe it's not a good first issue then. Thanks for considering 👍

Am 13. Juni 2023 18:34:54 MESZ schrieb Vedant Mistry ***@***.***>:
